permissoes:
  controllers:
##INICIO CHECKLISTS
    checklists:
      name: 'Checklists'
      actions:
        index:
          name: 'Visualizar'
          methods:
            - index
            - show
        new:
          name: 'Criar'
          methods:
            - new
            - create
        edit:
          name: 'Editar'
          methods:
            - edit
            - update
        change_status:
          name: 'Alterar Situação'
          methods:
            - change_status
### END CHECKLISTS

### START USUÁRIOS
    usuarios:
      name: 'Usuários'
      actions:
        index:
          name: 'Visualizar'
          methods:
            - index
            - show
        new:
          name: 'Criar'
          methods:
            - new
            - create
        edit:
          name: 'Editar'
          methods:
            - edit
            - update
        change_status:
          name: 'Alterar Situação'
          methods:
            - change_status
### END USUÁRIOS

### START AUDITORIAS
    auditorias:
      name: 'Pesquisas'
      actions:
        index:
          name: 'Visualizar'
          methods:
            - index
            - show
        new:
          name: 'Liberar Pesquisa'
          methods:
            - new
            - create
        edit:
          name: 'Responder Pesquisa'
          methods:
            - edit
            - update
        iniciar_pesquisa:
          name: 'Iniciar Pesquisa'
          methods:
            - iniciar_pesquisa
### END AUDITORIAS

### START RELATÓRIO
    relatorios:
      name: 'Relatórios'
      actions:
        pesquisas_respondidas:
          name: 'Pesquisas Respondidas'
          methods:
            - pesquisas_respondidas
        pesquisas_detalhadas:
          name: 'Pesquisas Detalhadas'
          methods:
            - pesquisas_detalhadas
### END RELATÓRIO

##INICIO NAO CONFORMIDADES
    nao_conformidades:
      name: 'Não Conformidades'
      actions:
        index:
          name: 'Visualizar'
          methods:
            - index
            - show
        new:
          name: 'Criar'
          methods:
            - new
            - create
        edit:
          name: 'Editar'
          methods:
            - edit
            - update
        destroy:
          name: 'Excluir'
          methods:
            - destroy
### END CONFORMIDADES
