permissoes:
  controllers:
##INICIO CHECKLISTS
    checklists:
      name: 'Checklists'
      actions:
        index:
          name: 'Visualizar'
          methods:
            - index
            - show
        new:
          name: 'Criar'
          methods:
            - new
            - create
        edit:
          name: 'Editar'
          methods:
            - edit
            - update
        change_status:
          name: 'Alterar Situação'
          methods:
            - change_status
### END CHECKLISTS

### START USUÁRIOS
    usuarios:
      name: 'Usuários'
      actions:
        index:
          name: 'Visualizar'
          methods:
            - index
            - show
        new:
          name: 'Criar'
          methods:
            - new
            - create
        edit:
          name: 'Editar'
          methods:
            - edit
            - update
        change_status:
          name: 'Alterar Situação'
          methods:
            - change_status
### END USUÁRIOS
