permissoes:
  controllers:
##INICIO CHECKLISTS
    checklists:
      name: 'Checklists'
      actions:
        index:
          name: 'Visualizar'
          methods:
            - index
            - show
        new:
          name: 'Criar'
          methods:
            - new
            - create
        edit:
          name: 'Editar'
          methods:
            - edit
            - update
        change_status:
          name: 'Alterar Situação'
          methods:
            - change_status
### END CHECKLISTS

### START USUÁRIOS
    usuarios:
      name: 'Usuários'
      actions:
        index:
          name: 'Visualizar'
          methods:
            - index
            - show
        new:
          name: 'Criar'
          methods:
            - new
            - create
        edit:
          name: 'Editar'
          methods:
            - edit
            - update
        change_status:
          name: 'Alterar Situação'
          methods:
            - change_status
### END USUÁRIOS

### START AUDITORIAS
    auditorias:
      name: 'Pesquisas'
      actions:
        index:
          name: 'Visualizar'
          methods:
            - index
            - show
        new:
          name: 'Liberar Pesquisa'
          methods:
            - new
            - create
        edit:
          name: 'Responder Pesquisa'
          methods:
            - edit
            - update
        inicir_pesquisa:
          name: 'Iniciar Pesquisa'
          methods:
            - inicir_pesquisa
### END AUDITORIAS
